name: Lint Docs

on:
  push:
    branches:
    - master
    paths:
    - "*.md"
    - "**/*.md"
    - ".github/workflows/docs-lint.yml"
  pull_request:
    paths:
    - "*.md"
    - "**/*.md"
    - ".github/workflows/docs-lint.yml"

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
    - name: Run Markdown linter
      run: |
        gem install mdl
        mdl README.md CHANGELOG.md
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
    - name: Lint Markdown files with RuboCop
      run: |
        gem install bundler
        bundle install --gemfile gemfiles/rubocop.gemfile --jobs 4 --retry 3
        bundle exec --gemfile gemfiles/rubocop.gemfile rubocop -c .rubocop-md.yml
  forspell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Hunspell
      run: |
        sudo apt-get install hunspell
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
    - name: Cache installed gems
      uses: actions/cache@v1
      with:
        path: /home/runner/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0
        key: gems-cache-${{ runner.os }}
    - name: Install Forspell
      run: gem install forspell
    - name: Run Forspell
      run: forspell README.md CHANGELOG.md
  lychee:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Link Checker
      id: lychee
      uses: lycheeverse/lychee-action@v1.5.1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        args: README.md CHANGELOG.md
